Drop database DQ_METADATA_NEW;
CREATE SCHEMA IF NOT EXISTS `DQ_METADATA_NEW`;
use DQ_METADATA_NEW;

CREATE TABLE `DATASTORE` (
 `ID` int(50) NOT NULL auto_increment,
 `NAME` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 `ZONE` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
 `CONN_TYPE` varchar(50)  	 CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
 PRIMARY KEY (`ID`)
);

CREATE TABLE `ENTITY` (
 `ID` int(50) NOT NULL  auto_increment,
 `NAME` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `SUBSIDIARY_NAME` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `DOMAIN_NAME` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `ZONE` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `TYPE` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `LOCATION` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
 `DATASTORE_ID` int(50) NOT NULL,
 `UNQ_ROW_ID` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 foreign key (`DATASTORE_ID`) references datastore(id),
 KEY `UK_ENTITY` (`DATASTORE_ID`,`UNQ_ROW_ID`,`NAME`)
);


CREATE TABLE `RULE_TYPE` (
 `ID` int(50) NOT NULL auto_increment,
 `NAME` varchar(500) COLLATE utf8_unicode_ci NOT NULL,
 `TEMPLATE_QUERY` varchar(6000) COLLATE utf8_unicode_ci DEFAULT NULL,
 `IMPLEMENTATION_NAME` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
 `DESCRIPTION` varchar(5000) COLLATE utf8_unicode_ci DEFAULT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 KEY `UK_RULE_TYPE` (`NAME`(255))
);



CREATE TABLE `RULE_TYPE_PARAMETER` (
 `ID` int(50) NOT NULL auto_increment,
 `RULE_TYPE_ID` int(50) NOT NULL,
 `NAME` varchar(128) COLLATE utf8_unicode_ci NOT NULL,
 `MANDATORY_FLG` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
 `DEFAULT_VALUE` varchar(128) COLLATE utf8_unicode_ci ,
 `CREATE_TS` timestamp NULL DEFAULT NULL,
 `UPDATE_TS` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`ID`),
 foreign key (`RULE_TYPE_ID`) references RULE_TYPE(ID),
 UNIQUE KEY `UK_RULE_TYPE_PARAMS` (`RULE_TYPE_ID`,`NAME`)
);
----------------



CREATE TABLE `RULE_ASSIGNMENT` (
 `ID` int(50) NOT NULL auto_increment,
 `DESCRIPTION` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
 `RULE_TYPE_ID` int(11) NOT NULL,
 `SEND_ALERT_FLG` char(1) COLLATE utf8_unicode_ci NOT NULL,
 `STOP_JOB_FLG` char(1) COLLATE utf8_unicode_ci NOT NULL,
 `TARGET_ENTITY_ID` int(11) NOT NULL,
 `SOURCE_ENTITY_ID` int(11) DEFAULT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `UPDATE_TS` timestamp NULL DEFAULT NULL,
 PRIMARY KEY (`ID`),
 foreign key (`RULE_TYPE_ID`) references RULE_TYPE(`ID`),
foreign key (`TARGET_ENTITY_ID`) references ENTITY(`ID`),
foreign key (`SOURCE_ENTITY_ID`) references ENTITY(`ID`)
);




CREATE TABLE `RULE_ASSIGNMENT_PARAMETER` (
 `ID` int(50) NOT NULL auto_increment,
 `RULE_ASSIGNMENT_ID` int(50) NOT NULL,
 `RULE_TYPE_PARAMETER_ID` int(50) DEFAULT NULL,
 `VALUE` varchar(1000) COLLATE utf8_unicode_ci NOT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UK_RULE_PARAMETER` (`RULE_ASSIGNMENT_ID`,`RULE_TYPE_PARAMETER_ID`),
 foreign key (RULE_ASSIGNMENT_ID) REFERENCES RULE_ASSIGNMENT(ID),
 foreign key (RULE_TYPE_PARAMETER_ID) REFERENCES RULE_TYPE_PARAMETER(ID)
);


CREATE TABLE IF NOT EXISTS `RULE_LOG` (
  `ID` varchar(500) NOT NULL,
  `RULE_ASSIGNMENT_ID` INT NOT NULL,
  `RULE_SET_ASSIGNMENT_ID` INT NOT NULL,
  `DATA_DT` DATETIME NOT NULL ,
  `RULE_START_TS` TIMESTAMP NOT NULL,
  `RULE_END_TS` TIMESTAMP NOT NULL,
  `BATCH_DT` VARCHAR(45) NULL,
  `TARGET_SQL_QUERY` VARCHAR(5000) NULL,
  `SOURCE_SQL_QUERY` VARCHAR(5000) NULL,
  `TARGET_RESULT_VALUE` VARCHAR(500) NULL,
  `SOURCE_RESULT_VALUE` VARCHAR(500) NULL,
  `RESULT` VARCHAR(45) NOT NULL,
  `STATUS` VARCHAR(45) NOT NULL,
  `PARTITION_TYPE` VARCHAR(45) NULL,
  `SEQ_NUM` INT NULL,
  `CREATE_TS` TIMESTAMP NOT NULL ,
  `UPDATE_TS` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_RULE_LOG_RULE1_idx` (`RULE_ASSIGNMENT_ID` ASC),
  CONSTRAINT `fk_RULE_LOG_RULE1`
    FOREIGN KEY (`RULE_ASSIGNMENT_ID`)
    REFERENCES `RULE_ASSIGNMENT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE `RULE_SET` (
 `ID` int(50) NOT NULL auto_increment,
 `NAME` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
 `CREATE_TS` timestamp NULL DEFAULT NULL,
 `UPDATE_TS` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
 PRIMARY KEY (`ID`),
 UNIQUE KEY `UK_RULE_SET` (`NAME`)
);


CREATE TABLE `RULE_SET_ASSIGNMENT` (
 `ID` int(50) NOT NULL auto_increment,
 `RULE_SET_ID` int(50) NOT NULL ,
 `RULE_ASSIGNMENT_ID` int(50) NOT NULL,
 `ACTIVE_FLG` varchar(1) COLLATE utf8_unicode_ci NOT NULL,
 `EXPIRED_TS` timestamp NULL DEFAULT NULL,
 `CREATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 `UPDATE_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
 PRIMARY KEY (`ID`),
 foreign key (RULE_SET_ID) references RULE_SET(ID),
 foreign key (RULE_ASSIGNMENT_ID) references RULE_ASSIGNMENT(ID),
 UNIQUE KEY `UK_RULE_SET_ASSIGNMENT` (`RULE_SET_ID`,`RULE_ASSIGNMENT_ID`)
);
